### ISSUE TITLE
Link validation

### ISSUE THREAD

**Issue by h1alexbel** [h1alexbel/h1alexbel.github.io#268]
Let's validate links I refer to

**Comment by h1alexbel** [comment]
can be done using the following GHA:

```yml
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Check links
      uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        use-quiet-mode: yes
        use-verbose-mode: yes
        config-file: .mdlc.json
```
